netsec-ethz/scion

go/border/netconf/interface.go
go/lib/topology/topology.go
python/beacon_server/base.py

* InternalAddressIdx not properly initialised
* Superfluous check for InternalAddresses compared pointer instead of
values, plainly rejecting everything
* Beacon Server did not send IFID packets to correct internal address
Note: still only works properly if a separate internal address is configured
per interface, otherwise the IFID packets are not correctly forwarded.
This appears to have been fixed on the scionproto master branch (in #1587).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/4)

Fix support for multiple interfaces on BR

---

topology/PathPolicy.yml

- Accept any PCB that's <= 4 hours old (increased from 60s)
- Allow segments with 30 hops (increased from 10), as the core in the
beginning may not be very tightly meshed.
Closes #6 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/13)

Set PathPolicy defaults to saner values. (#1741)

---

python/scion_elem/scion_elem.py

Known problem:
- All the incoming packets are stored in a single queue(packet buffer) regardless of their types
- The default size of the queue is 50
- SCIONLab used to propagate more than 50 PCBs at a time
- The surge of PCB packet transmission might cause a lot of packet drops
Driven by the problem, we decided to increase the size of queue up to 5000.
This change has been tested in real environment, and approved to be applied to the ScionLab nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/16)

Increase the size of packet buffer up to 5000

---

python/lib/path_store.py
python/test/lib/path_store_test.py

From https://github.com/scionproto/scion/pull/2076
If a PCB arrives with a timestamp from the future (which is accepted
due to the changes in #1990), it may result in a zero delay_time value.
The delay_time value is used in a division in the fidelity computation,
which will trigger an exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/17)

Cherry-pick to scionlab: Fix delay_time computation to avoid division by zero

---

env/debian/pkgs.txt
scion.sh

For the scionlab installations, we prefer to run zookeeper directly on the host as opposed to running it in a container via docker-compose.
This PR adds back the old logic for running the zookeeper via systemd.
This change was not accepted in upstream; the preference is to use docker for this and NOT to use scion.sh for production environments in the first place.
The medium term plan is for scionlab to avoid using scion.sh and this dev environment by switching to prebuilt binary packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/19)

Add non-docker option for zookeeper back

---

go/border/rpkt/rpkt.go

Workaround for messages from the (core-) path server being too large to
fit into a single message. The long-term fix will be to adopt a reliable
transport protocol for the path server messages.
Increasing pktBufSize will increase the memory usage for the border
routers. After some testing, this seemed acceptable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/21)

Workaround for many paths: set pktBufSize to 64KiB

---

go/lib/infra/modules/combinator/graph.go
go/path_srv/internal/handlers/segreq.go
go/path_srv/internal/handlers/segreqcore.go
go/path_srv/internal/handlers/segreqnoncore.go
go/path_srv/internal/handlers/segreqnoncore_test.go

Return segments corresponding to connected paths with least number of
hops, using path combinator to find valid combinations of segments.
See scionproto/scion#2452 -- will most likely not be merged in upstream as a larger reorganization of the PS lookups is planned (scionproto/scion#2454).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/23)

Limit number of segments returned

---

go/lib/spath/path.go
go/tools/showpaths/paths.go

Updates spath incOffsets for the Hop Field offset increment to allow NOT skipping non routing Hop Fields.
Add a flag to showpaths that uses this to show details about the Hop Fields of a path.
Is useful to verify that paths that look identical at the Interface level are different at the Hop Field level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/25)

Add verbose flag for Hop Fields to showpaths

---

go/border/rctrl/ctrl.go

When sending big IFState packets from the BS to the BR, the BR will need
more room in its buffer. This is a similar patch to the one applied in
the data plane via PR #21.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/28)

Control plane buffer size also to 64K.

---

go/cert_srv/internal/csconfig/conf_test.go
go/cert_srv/internal/csconfig/sample.go
go/path_srv/internal/psconfig/sample.go
go/path_srv/internal/psconfig/sample_test.go
go/sciond/internal/sdconfig/sample.go
go/sciond/internal/sdconfig/sample_test.go
go/sig/internal/sigconfig/conf_test.go
go/sig/internal/sigconfig/sample.go

Leave the log section identical for all the toml configuration samples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/30)

Same log sample section for all

---

python/beacon_server/base.py
python/beacon_server/if_state.py
python/scion_elem/scion_elem.py

Updating the timestamp is very cheap (same order of magnitude as        enqueuing the packet for asynchronous processing), so it can safely be        done on the packet-receive thread.
This helps to process IFID packets for active interfaces in time, as it        and avoids the problem that interfaces time out because the IFIDs are        stuck in a long packet processing queue (behind PCBs).
For inactive interfaces, the processing of the IFIDs is more work as        state updates will be sent out. Also, this is not time-critical as the        interface is, well, down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/27)

Fast path handling for IFIDs

---

scion.sh

After generating a new topology the file zk-dc.yml always exists. Accept a parameger when
calling 'topology' to remove said fail right after generating the new topology. This
will prevent run_zk from calling docker compose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/31)

Accept a parameter to avoid calling docker compose.

---

python/integration/set_ipv6_addr.py

A utility for the integration tests fails loudly during `scion.sh start` if this `gen/overlay` is missing, but this has no effect whatsoever for actually running scion.
Allows to not include this otherwise useless file in the scionlab config tarball.
Fixes netsec-ethz/scionlab#87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/35)

Ignore missing gen/overlay file

---

python/scion_elem/scion_elem.py

Prevents the BS from crashing when the previous TRC cannot be found
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/36)

Fix typo in error handling

---

python/topology/zk.py
scion.sh

Don't create zk-dc.yaml in topology creation so that `scion.sh start` will default to start the system zookeeper.
This is a follow up on #19.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/40)

Use system zookeeper by default in local topo

---

go/lib/infra/modules/trust/trust.go

In SCIONLab the clocks are not well synchornized. We allow up to 10 seconds difference
among clocks in different machines.
This particular patch relies on  instead of modifying the
default values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/58)

Allow clock drifts up to 10 seconds.

---

python/topology/zk.py

The `zk-dc.yml` file is needed by the integration tests when running inside a docker container.
Use the `args.in_docker` to detect that situation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/56)

Fix zookeeper conf creation in CI

---

python/lib/packet/packet_base.py

When running an AS with the next SCIONLab version, the BS in this AS will crash every ~30 secs. Simply avoid the crashing, as it is interesting for us to upgrade machines gradually, and not all at once, if possible.
To test it, e.g. run a user AS following `scionlab_nextversion`, attached to a current `scionlab`. The `BS` of the AP will restart frequently (check with `supervisor.sh status`).
The original exception is:
```
2019-08-20 14:39:07.023691+0000 [CRITICAL] (Elem.packet_recv) Exception in Elem.packet_recv thread:
2019-08-20 14:39:07.028820+0000 [CRITICAL] (Elem.packet_recv) Traceback (most recent call last):
2019-08-20 14:39:07.029960+0000 [CRITICAL] (Elem.packet_recv)   File "capnp/lib/capnp.pyx", line 1354, in capnp.lib.capnp._DynamicStructBuilder._which …
```

Prevent BS crash.

---

go/lib/infra/modules/segverifier/segverifier.go
go/lib/infra/modules/trust/signhelper.go

It has been discovered TRCs are verified only against local trust store even if the packet is signed with a TRC which is newer than one available in the store.
This provides a workaround for this issue also fixing an underlying bug where TRCVer is ommited during segment verification.
Closes-Bug: ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/60)

Improve Segment verification

---

go/lib/infra/modules/trust/signhelper_test.go

Git bisect showed that we broke a UT in `2b09bca57313b27e6cb1b443e8b0040fb2c8be39` .
This fix adds a valid TRC in the trust DB so that the validation won't fail because a TRC not found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/62)

The UT needs a TRC in the trust DB

---

env/debian/pkgs.txt
scion.sh

Not needed anymore. We don't typically need zookeeper anyway so no need for this special setup anymore.
In particular, this removes zookeeper from dependencies.
This reverts #19
This reverts commit b1711994926b8b5ceab8d4df9f9b4be5084d27e5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/netsec-scion/66)

Revert "Add non-docker option for zookeeper back"

---

go/cert_srv/internal/drkey/store_test.go
go/lib/drkey/epoch.go

It fails ~ 1 / 2000 times otherwise. 
It should be visible with `bazel test  //go/cert_srv/internal/drkey:go_default_test --runs_per_test=20000` ; that's 20k runs of the test functions.
Because we don't want to add sync primitives in the store only to be able to UT it, we split the test in two: check that the ticker runs when the store is created, and check that when the clean function is called it removes the expired keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/71)

Make the DRKey SV store ticker UT more robust.

---

README.md

Based on current scionproto/scion:master version; add description of what this fork is about, clarify where to contribute and where to find docs.
Fixes #72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/76)

README: what's this fork

---

go/pkg/router/control/bfd.go

This is temporary (tm).
Issue scionproto/4019 reports a problem with the BFD
packets when the border router is under heavy load.
To temporarily workaround this issue, set the default value
of the detection time multipler to 100, instead of 3.
Since most configuration in scionlab do not specify values
for BFD, the detection time will be 100 * tx_interval =
100 * 200ms = 20s .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/89)

Workaround for issue scionproto/4019.

---

go/pkg/cs/drkey/grpc/drkey_fetcher.go
go/pkg/cs/drkey/grpc/drkey_service.go

This condition is now handled analog to a similar condition in github.com/scionproto/scion/go/pkg/trust.AuthRouter.ChooseServer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/90)

cs/drkey: handle situations where no path to a peer AS can be found

---

go/daemon/main.go

The DRKey store is not being passed to the daemon server,
always resulting in DRKey being disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/108)

Fix broken DRKey.

---

go.mod
go.sum

This is the result of running `go mod vend` on the source code. Without
this, we can't build from source without errors from go, because the
lockfile (go.mod/go.sum) has not been properly committed in this git
history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/109)

go: update go.mod/go.sum

---

go/dispatcher/dispatcher/BUILD.bazel
go/dispatcher/dispatcher/underlay.go
go/pkg/router/colibri_processing.go

Currently there is a problem when running Colibri in the local scion setup, which is running only a single dispatcher serving multiple ASes. Example for the tiny topology:
If a Colibri control packet is sent on the path `112->110->111` (destination AS = `AS 111`), then the packet is correctly forwarded at the ingress BR of `AS 110` to the IP of the host running the Colibri service (because `C = 1`). However, in the local test setup, the dispatcher then tries to find which AS is hosting the Colibri service, and it thinks it is `AS 111`, as this is the destination AS in the packet header.
We want the packet to arrive at the Colibri service of `AS 110`.
Considered solutions:
- Run one dispatcher per AS.
- Let the ingress BR overwrite the destination ISD/AS with its local ISD/AS.
The solution …

colibri: add support for a single dispatcher serving multiple ASes.

---

go/pkg/router/dataplane_test.go

Fixes https://github.com/netsec-ethz/scion/issues/119.
The tests need to be adapted because https://github.com/netsec-ethz/scion/pull/116 changed the timestamp field in Colibri control packets (C=1) to carry the local ISD/AS identifier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/120)

Colibri: Fix failing tests.

---

go/co/main.go
go/cs/main.go

Closes #85 
Due to a slight oversight the DRKey TLS server is not gracefully shutdown. This prevents the CS from finishing cleanly.
The COLIBRI service was never gracefully terminated, now it is. Also its DB is closed appropriately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/124)

shutdown gracefully CS and COL

---

go/co/main.go
go/coligate/processing/BUILD.bazel
go/coligate/processing/export_test.go
go/coligate/processing/forwarder.go
go/coligate/processing/processing.go
go/coligate/processing/processing_test.go
go/coligate/processing/processor.go
go/coligate/processing/processor_test.go
go/coligate/storage/storage.go
go/coligate/storage/storage_test.go
go/pkg/co/colibri/grpc/BUILD.bazel
go/pkg/co/colibri/grpc/colibri_service.go
go/pkg/coligate/config/coligate.go
go/pkg/coligate/grpc/BUILD.bazel
go/pkg/coligate/grpc/coligate.go
go/pkg/coligate/observability.go
proto/colibri/v1/colibri.proto

This Pullrequest contains several implementation changes that lead to better performance and benchmark tests.
- cache ciphers, delete sigmas
- reuse grpc clients for update sigmas
- change reservation id mapping from string to [12]byte
- improve performance of cleanup routine
- introduced packet forwarder
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/149)

colibri gateway performance improvements

---

go/pkg/router/dataplane.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/156)

Directly send time sync packets to egress interface without queueing.

---

.bazelrc
private/storage/db/BUILD.bazel
private/storage/db/sqlite_mattn.go
private/storage/db/sqlite_modernc.go

Use the older sqlite library from mattn repository as default.
Mitigates #166
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/167)

Mattn's sqlite as default

---

pkg/addr/fmt.go
private/path/fabridquery/parser.go

Fixes the issue introduced in https://github.com/netsec-ethz/scion/pull/168/commits/bf6678297e16f3b49c3585d4137ecac1374af616, where the ParseASSep function was removed, but the function calls to the function were still present. This new commit uses the formatting functions already present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/171)

fix: Parsing the AS with the built-in parsing function

---

doc/dev/design/FABRID.rst

Updated the configuration entries for the control service and the border router, added the configuration entry for the daemon and fixed some typos.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/172)

Fabrid design doc update

---

private/app/path/path.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/netsec-ethz/scion/177)

fix fabrid path.Choose in case where there are no fabrid paths satisfying the query
